### ISSUE TITLE
Chart-Daten verfügbar machen

### ISSUE THREAD

**Issue by Snapergy** [Morluktom/ioBroker.lg-ess-home#10]
Im entsprechenden Thread im IoBroker-Forum wurde als zukünftige Arbeit die Auswertung der Chart-Daten in Aussicht gestellt. Ist dies in naher Zukunft möglich? Ich interessiere mich dafür die Charts auch auf meiner Vis darstellen zu können. Dies würde eine komplizierte, eigenständige Datenhaltung verhindern.

**Comment by fu-zhou** [comment]
Hey, das neue Widget in der 0.2 ist ja der Knaller, vielen Dank dafür! Kann man im Kalender ggf. noch die letzten 12 Monate einstellen neben dem aktuellen Jahr?

**Comment by Morluktom** [comment]
Servus,

Ich möchte noch einen beliebigen Zeitraum einfügen.
Ist angedacht.

Gruß 
Tom

**Comment by thetimmyventura** [comment]
Hi!
Vielen Dank für das Widget, sehr geil! Hat sofort alle anderen Versuche der Darstellung ersetzt.

Eine kleine Änderung würde ich mir wünschen:
In der Tagesansicht der Energieansicht sind die Zeitstrahlen oben und unten (Erzeugung vs. Verbrauch) horizontal nicht deckungsgleich, weil sich rechts oben die Legende des Ladestands befindet.
lg

**Comment by Morluktom** [comment]
Hi,
Danke für die Rückmeldung.
Ich überarbeite gerade das linke Menü, das gefällt mir so nicht.
In diesem Zuge werde ich das mit anpassen.

Folgende Erweiterung sind noch geplant:
- Anzeige beliebiger Zeitraum/Tag
- Integration Solcast(PV Vorhersage)
- Möglichkeit für Zoom der Chart Daten 


Gruß 

Tom
