### ISSUE TITLE
Batteriebetrieb temporär deaktivieren

### ISSUE THREAD

**Issue by fu-zhou** [Morluktom/ioBroker.lg-ess-home#11]
Hallo mal wieder,
ich fange irgendwann einmal an, ein E-Auto zu Hause zu laden. Dabei will ich vermeiden, dass die LG Batterie in die Autobatterie entladen wird. Im Adapter gibt es das Objekt lg-ess-home.0.user.essinfo.home.operation.mode welches "Stop", "Normal Mode" oder "PV only mode" sein kann. Allerdings ist das Objekt eine reine Anzeige. Gibt es unter "Commands" die Möglichkeit, in den "PV only mode" zu wechseln, die Batterie also zu deaktivieren? In der App geht das unter "Installateur Einstellungen -> Akku".

**Comment by fu-zhou** [comment]
Hallo Tom, ich würde das auch gerne mal probieren. Im September gab es eine neue Firmware, ggf. hat sich das Verhalten geändert, ist bei LG ja leider nicht dokumentiert, was von FW zu FW passiert. Welches Objekt muss ich wie einstellen, um die Batterie über ioBroker zu (de-)aktivieren?

Danke vorab!

**Comment by Morluktom** [comment]
Hallo,
Die Möglichkeit muss ich erst implementieren. Ich werde es in den nächsten Wochen mal integrieren.
Gruß 
Tom

**Comment by fu-zhou** [comment]
Hallo Tom, ich dachte, zum Jahrestag melde ich mich mal wieder. Bist du hier schon einen Schritt weiter? Was jetzt noch dazu käme wäre die Möglichkeit, in der aktuellen Jahreszeit die Batterie über Nacht aus dem Netz zu laden, um auf ein Blackout vorbereitet zu sein. Gibt es da was? Bei der Systeminitialisierung in der App wird die Batterie kurz aus dem Netz geladen und auch jetzt bei leerer Batterie wird immer wieder mal 4 kW für eine kurze Zeit reingeladen, ich nehme an, zur Pflege.

**Comment by Morluktom** [comment]
Hallo,
Da gibt LG keine Möglichkeit dazu. Meines Wissens ist das auch Rechtlich untersagt.
Es darf soweit wie ich weiß nur eine kurze Notfallladung ausgeführt werden.
Gruß 
Tom

**Comment by fu-zhou** [comment]
Jetzt habe ich nach 14 Monaten meine E-Karre gekriegt und ich kann das Rumspielen natürlich nicht sein lassen. Eine Möglichkeit, die Batterie beim Laden des Autos vor Entladung zu schützen ist, den Backup-Mode über lg-ess-home.0.commands.BackupMode zu aktivieren und in der App den Backup-Modus-SOC auf Maximum (=80%) zu stellen. Dann wird zwar immer noch bis 80% entladen, aber besser als ganz leer machen. Die 80% werden von der App verriegelt, aber es lässt sich über den Adapter kein Wert eintragen, lg-ess-home.0.installer.setting.batt.backup_soc steht auf "write : false". Aber selbst wenn ich das auf "write : true" ändere, kommt im LG-ESS (in der App) nichts an, auch nicht angemeldet als Installateur im Adapter. Meine Idee wäre nämlich, dass ich über den Backup-Modus-SOC die Batterie-Entladung sperre, also: Auto wird geladen => Backup-Modus-SOC = 100%, Auto wird nicht geladen: Backup-Modus SOC = 0% und der Backup-Mode bleibt immer aktiviert. Alternativ: wie jetzt (Backup-Mode ON/OFF) aber die 80%-Grenze in der App würde ich gerne mit dem Adapter überlisten, um einen höheren Wert einstellen zu können (wenn das das LG-ESS zulässt).

Was hältst du von dem Workaround? Kannst du den Backup-Modus-SOC über den Adapter bedienbar machen?

**Comment by fu-zhou** [comment]
Hallo Tom, kannst du dir das mal anschauen (s.o. - Backup-Modus-SOC nicht schreibschützen)?

Danke vorab und frohe Ostern!

**Comment by Morluktom** [comment]
Hi,Sehe ich mir demnächst mal an.Gruß TomMit freundlichen Grüßen Thomas MayerFliederweg 583134 Prutting

**Comment by fu-zhou** [comment]
Danke schon mal, vielleicht willst du deine Adresse hier noch rausnehmen?

**Comment by diehappy69** [comment]
Hi,
gibt es Neuigkeiten zu dem Thema? Ich würde gerne einen dynamischen Stromtarif für die Wallboxen verwenden und die Batterieentladung unterbinden, wenn das Auto anfängt zu laden. 

Kann ich den Backupmodus im Installermenü aktivieren, auch wenn ich keine Notstromversorgung habe?

Neben Iobroker ist auch Evcc im Einsatz, um das ganze dynamisch zu steuern. Gibt es für die Batteriesteuerung schon eine funktionierende Implementierung?
Dank Euch

**Comment by Morluktom** [comment]
Hi, die einzige Möglichkeit die ich bis jetzt sehe, ist in den Installateur Einstellungen das vorhanden sein einer Batterie zu deaktivieren.
Das habe ich auch schon probiert und das würde auch gehen.
ABER: Auch wenn dann die Batterie wieder aktiviert wird, sie entlädt erst wieder wenn Energie von der PV kommt. D.h unter Umständen legst Du den Akku für eine ganze Nacht lahm => Das will ich nicht integrieren.
Mit dem Sunspec Protokoll bin ich nicht weiter gekommen. 
Gruß
Tom

**Comment by diehappy69** [comment]
Der Weg über den Backup Modus ist keine Alternative? Das hätte den Vorteil, dass ggf. die Batterie von der PV geladen wird.

**Comment by NI07077** [comment]
Hey, 
sag mal wäre es möglich in den installer Settings die Punkte:
 
lg-ess-home.0.installer.setting.batt.max_operation_range
lg-ess-home.0.installer.setting.batt.min_operation_range

unter commands als Writeable aufzunehmen?

Meine Idee bzw. Workaround:
1. Über: lg-ess-home.0.commands.Operation den Systembetrieb stoppen (ähnlich wie über die App)

2. durch Verringerung von: lg-ess-home.0.installer.setting.batt.max_operation_range die zur Verfügung stehende Batterieleistung künstlich zu begrenzen und so ein Entladen zu verhindern.
=> E-Auto könnte nachts ohne Entladung der Batterie geladen werden.

3. durch Erhöhen von: lg-ess-home.0.installer.setting.batt.min_operation_range ggf. eine Zwangsladung aus dem Netz provozieren.
=> bei dynamischen Stromtarif könnte evtl. die Batterie nachts getriggert werden eine Notaufladung vorzunehmen.

**Comment by Morluktom** [comment]
Hallo,

Am Modbus bin ich gerade dran. Habe aber auch noch keine Vorteile gefunden.
Zu den beiden Werten welche Du vorgeschlagen hast. Ich denke das wird nicht funktionieren, diese sind in der App nur Anzeigewerte. 
Ein Entladen des Akkus kann denke ich über denn Backup Modus verhindert werden, ein gezieltes Laden aus dem Netz ist außer über die Betriebstest Funktion nicht möglich.
Ich hoffe da kommt noch ein Update von LG.
Den Backup Modus werde ich demnächst umsetzen.

Gruß
Tom

**Comment by NI07077** [comment]
Hey,
schade, dass es nur Anzeigewerte sind. Das mit der Integration der Backup Funktion ist aber schonmal schön zu hören!
Weitere Idee:
1. Systembetrieb per App stoppen. Wechsel in die Installaterfunktionen in der App.
2. Anstelle des Betriebstest die minimale Operationrange des Akku auf Testweise 50% erhöhen? Schauen ob das ein Trigger für die Ladung des Akkus aus dem Netz ist. Oder lässt sich das in der App auch nicht verändern?

Ich habe leider gerade physisch keine LG ESS vor mir. Müsste man aber mal ausprobieren.

**Comment by NI07077** [comment]
Kurzer Nachtrag: Der Betriebsbereich des Akku ist 10% - 100% und ist auch in den Installateureinstellungen nicht veränderbar... Bleibt also erstmal nur den Weg das Entladen des Akkus durch die Aktivierung des Backupmodus temporär zu verhindern.

**Comment by diehappy69** [comment]
Kann ich den Backupmodus anwählen ohne das ich die Ewitec Box zur Notstromversorgung habe?

**Comment by Morluktom** [comment]
Sollte mittels anheben des Backup SOC mit der Version 0.4.0 jetzt möglich sein
