### ISSUE TITLE
0.1.0: Kommunikationsabbruch kurz nach starten des Adapters

### ISSUE THREAD

**Issue by fu-zhou** [Morluktom/ioBroker.lg-ess-home#12]
Hallo, habe heute den Adapter 0.1.0 installiert und festgestellt, dass er kurz nach dem Start von grün auf gelb zurückspringt und im Log Folgendes steht:
`<html>
<body>

lg-ess-home.0 | 2021-11-28 14:02:12.343 | info | [LG ESS] Login faild: {"code":"ESOCKETTIMEDOUT","connect":false}. Try again in one Minute
-- | -- | -- | --
lg-ess-home.0 | 2021-11-28 14:02:12.338 | warn | [LG ESS] Error: {"code":"ESOCKETTIMEDOUT","connect":false}

</body>
</html>`

zurück auf 0.0.10 läuft der Adapter wieder.

Scheinbar konkurriert der Adapter 0.1.0 auch mit der App, die beschwert sich nämlich, dass ein anderer Installateur zugreift, solange der Adapter grün ist.

Meine Einstellungen sind:
![image](https://user-images.githubusercontent.com/11984960/143769226-173ef519-dc73-4fe8-9341-7b37062c2978.png)

Ich kann (fast) jederzeit testen!

**Comment by fu-zhou** [comment]
noch eine Ergänzung: wenn man in der App im Installateur-Bereich - weitere Funktionen - Fernbedienung auf SunSpec einstellt, geht auch der Adapter 0.0.10 auf gelb. Bei zurückstellen auf "keiner" wird er wieder grün.

**Comment by Morluktom** [comment]
Da der Adapter über die gleiche Schnittstelle wie die App zugreift, kann als Installateur nur einer zugreifen. Sobald du in die App gehst fliegt der Adapter raus. Der sollte aber dann sich wieder verbinden wenn die App verlassen wird. 
Du hast das SunSpec aktiv, hast Du den Zugriff schon geschaft? Ich scheitere im Moment noch dran.

**Comment by fu-zhou** [comment]
Adapter fliegt raus, die App beschwert sich parallel auch und hat keinen Zugriff. Bei der 0.0.10 gabs das Verhalten nicht. Vielleicht wäre in der Adapterkonfiguration ab 0.1.0 "Installateur-Einstellungen aktiv - ja/nein" möglich, so dass man das Verhalten bewusst beeinflussen kann.
Ich habe mit SunSepc noch keinen Erfolg gehabt, im Gegenteil: Auf einmal ist die App (V1.3) auf sämtlichen meiner Andoid Geräten abgestürzt (weißer Bildschirm => App geschlossen), egal ob über LAN oder das LG ESS Wlan. Ich habe dann eine alte Firmware über USB-Stick installiert, jetzt wird aber die aktuelle Firmware nicht mehr über Internet oder Stick installiert und der Wechselrichter erzeugt keinen Strom mehr. Habe schon einen SR bei LG eröffnet und da auch gleich nach der SunSpec-Spezifikation gefragt - keine Antwort bisher.

Mit Startgenehmigung wäre ich gestern Abend im Orbit angelangt..

Zu SunSpec nochmal: Modbus TCP (Port 502) scheint mit aktivem SunSpec aktiv zu sein, jedenfalls verbindet ein Modbus-Client, "vernünftige" Antwort kommt aber nicht...

**Comment by fu-zhou** [comment]
Habe mal einen Modubus Scanner über die IP des LG ESS laufen lassen, sieht dann so aus:
![image](https://user-images.githubusercontent.com/11984960/144112150-2b321977-739d-4426-a6b6-7a5ec17002b9.png)
und es macht auch keinen Unterschied, ob SunSpec aktiviert ist, oder nicht. Wenigstens hätte ich erwartet, dass der Port 502 dann zu ist und keine Antwort gibt...

**Comment by Morluktom** [comment]
Wenn du beim Adapter 0.1.0 den Haken bei als Instalateur anmelden raus nimmst dann sollte der Adaper gleich sein wie 0.0.10 nur inkl. der Chart Daten.

Mit dem Modbus bin ich genau so weit wie Du.
Mich wundert das sich Port 502 verbinden lässt bekomme auch unter keiner Device ID auf die Anfragen.
Laut der Smartfox Beschreibung müsste der Wechselrichter die 1 haben
Die Doku für Sunspec habe ich. Das gefällt mir gut, wäre universell einsetzbar.

**Comment by fu-zhou** [comment]
Habe jetzt auf die 0.1.0 umgestellt, aber der Graph-Ordner fehlt...

**Comment by fu-zhou** [comment]
Heute ist eine neue Firmware bei mir drauf gebügelt worden, es scheinen noch mehr bzw. alle PCS Parameter freigegeben zu sein (in der App nicht mehr ausgegraut), so auch PCS - System 2 - Akku Lade- und Entladebegrenzung, Habe aber nicht nicht probiert, ob man die über die App verstellen kann (System muss ja gestoppt werden).
Aber: Der Adapter 0.1.0 will mit der neuen Firmware nicht, er steigt immer wieder aus:
`<html>
<body>


lg-ess-home.0 | 2021-12-01 16:04:19.805 | info | [LG ESS] Login success.
-- | -- | -- | --
lg-ess-home.0 | 2021-12-01 16:04:18.649 | info | starting. Version 0.0.10 in /opt/iobroker/node_modules/iobroker.lg-ess-home, node: v12.22.7, js-controller: 3.3.21
lg-ess-home.0 | 2021-12-01 16:04:14.228 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
lg-ess-home.0 | 2021-12-01 16:04:14.227 | info | terminating
lg-ess-home.0 | 2021-12-01 16:04:14.223 | info | Got terminate signal TERMINATE_YOURSELF
lg-ess-home.0 | 2021-12-01 16:04:03.717 | info | [LG ESS] Login faild: {"code":"ESOCKETTIMEDOUT","connect":false}. Try again in one Minute
lg-ess-home.0 | 2021-12-01 16:04:03.715 | info | [LG ESS] Login faild: {"code":"ESOCKETTIMEDOUT","connect":false}. Try again in one Minute
lg-ess-home.0 | 2021-12-01 16:04:03.709 | info | [LG ESS] Login faild: {"code":"ESOCKETTIMEDOUT","connect":false}. Try again in one Minute
lg-ess-home.0 | 2021-12-01 16:04:03.651 | info | [LG ESS] Login faild: {"code":"ESOCKETTIMEDOUT","connect":false}. Try again in one Minute
lg-ess-home.0 | 2021-12-01 16:04:03.528 | info | [LG ESS] Login faild: {"code":"ESOCKETTIMEDOUT","connect":false}. Try again in one Minute
lg-ess-home.0 | 2021-12-01 16:04:03.247 | warn | [LG ESS] Error: {"code":"ESOCKETTIMEDOUT","connect":false}


</body>
</html>`

**Comment by fu-zhou** [comment]
Ladebegrenzung kann bei deaktiviertem System jetzt in der App verändert werden. Konnte es aber noch nicht in der Praxis probieren, mein Akku war schon länger nicht mehr voll...

**Comment by fu-zhou** [comment]
kurze Info: Email vom LG-Service:
_Nach Aufschaltung unseres Headquarters auf Ihre Anlage wurde ein Firmwareupdate auf die aktuelle experimental Firmware [R1431] durchgeführt_

**Comment by Morluktom** [comment]
Danke für die Info. Mit Modbus bist Du auch noch nicht weiter gekommen?

**Comment by fu-zhou** [comment]
Leider überhaupt nicht, ich Rahmen des Firmwareupdates habe ich LG gegenüber noch einmal meine Verwunderung zum Ausdruck gebracht, dass es kommerzielle Produkte gibt, die mit dem LG WR über SunSpec kommunizieren, es aber keine Beschreibung dazu gibt, wie es bei anderen Herstellern der Fall ist.

**Comment by fu-zhou** [comment]
bin jetzt nochmal auf die 0.1.0 hoch und habe SunSpec eingeschaltet, bisher läuft der Adapter stabil (als user, nicht installer). Ich weiß langsam nicht mehr, was Sache ist...

**Comment by fu-zhou** [comment]
ich glaube, ich weiß jetzt, was Sache sein könnte: Wenn ich SunSpec im LG ESS wieder ausschalte, fängt danach der Adapter (und ich glaube auch die App) zu spinnen an: Verbindung wird aufgebaut und danach sofort wieder gekappt. Erst wenn man einmal einen Neustart vom LG gemacht hat, ist wieder alles grün. Beim Aktivieren von SunSpec passiert das nicht, d.h. mit dem Adapter 0.1.0 ist erst einmal alles in Ordnung, würde ich sagen.

**Comment by fu-zhou** [comment]
Seit mein Android Telefon vor einiger Zeit vorgeschlagen hat, die LG Enervu App ins "tiefe Standby" zu versetzen und ich das auch gemacht habe, funktioniert der Adapter einwandfrei - ob's tatsächlich am tiefen Standby liegt kann ich nur vermuten, aber ich traue der App sehr wohl zu, dass sie beim normalen Beenden im Hintergrund weiter kommuniziert und es deshalb zu Interferenzen mit dem Adapter kommt... Mit Sunspec geht es irgendwie so gar nicht weiter, LG rückt irgendwie nix raus (Doku oder so)
