### ISSUE TITLE
GET Request liefert nur 404 

### ISSUE THREAD

**Issue by Bhenyamin** [Morluktom/ioBroker.lg-ess-home#16]
Ich kann mittels GET Request einfach kein Passwort auslesen. 
Habe einen einfachen REST-Client auf dem Android Smartphone laufen, und mich mit dem WLAN des ESS verbunden. 
Habe die beiden Head Parameter eingetragen und als body "key": "lgepmsuser!@#!"
Ich erhalte im Response keinen Body zurück und einen 404 Fehler. 
Wie komme ich dahinter?

**Comment by Morluktom** [comment]
Hallo, welchen REST Client verwendest Du? 
Dann versuch ich das mal mit dem.

**Comment by Morluktom** [comment]
Und Du bist auch sicher mit WLAN des ESS verbunden? D.h Du hast die Taste am Wechseleichter gedrückt und dich dann direkt mit dem Hotspot verbunden?

**Comment by Bhenyamin** [comment]
Moin, ich nutze Restler für Android. 
Anbei mal Screenshots von den Einstellungen in der App. Ja, ich verbinde mein Android Handy mit dem ESS AP welcher nach Halten der WLAN Taste da ist (WLAN Schriftzug wird blau). Da bin ich auch sicher verbunden.  
![Screenshot_20221130-215428](https://user-images.githubusercontent.com/101006541/204906691-845a6c0a-ea63-4829-baf0-eb74e5b550d9.jpg)
![Screenshot_20221130-215436](https://user-images.githubusercontent.com/101006541/204906693-32739366-3b05-41a8-9bc0-9b30218cac6c.jpg)

**Comment by Bhenyamin** [comment]
Darf ich das nochmal pingen?

**Comment by grex1975** [comment]
Hallo Bhenyamin,
probiere bitte noch folgendes:
POST request statt GET
den body in {} setzen, also so: {"key":"lgepmsuser!@#"}
Wenn das nicht funktioniert, probiere ich es bei mir noch einmal aus.
LG, Grex

**Comment by Bhenyamin** [comment]
Yeah! Danke! DAS war es! Perfekt

**Comment by grex1975** [comment]
Freut mich :-)
@Morluktom: kannst du bitte diese beiden Änderungen auf die Hauptseite übernehmen?
Danke,
Grex
