### ISSUE TITLE
Aktualisieren von Datenpunkten, v.a. user-setting funktioniert nicht verlässlich

### ISSUE THREAD

**Issue by fu-zhou** [Morluktom/ioBroker.lg-ess-home#3]
Hallo Tom, ich habe den Adapter 0.0.5 jetzt ein paar mal installiert, zum Teil innerhalb eines Systems (de-install - install zum Testen), zum Teil auf einem neuen System. Bei einem System werden die Datenpunkte in ioBroker befüllt, beim anderen nicht ganz. Ich habe jetzt ein System (Ubuntu 20) taufrisch aufgesetzt und da bleiben einige Datenpunkte leer, auch die, die auf dem anderen System schon zu sehen waren, wie z.B. Versionsnummern der Firmware oder die Netzwerk-Konfiguration. 
![Bild1](https://user-images.githubusercontent.com/11984960/102774490-63465180-438b-11eb-808e-a9a473aeaa5b.png)
Hast du eine Idee?

**Comment by Morluktom** [comment]
Hallo,
Was ich sehen kann das die alle vom Typ Value sind sollten aber text sein.
Muss ich mir ansehen warum er da falsche Datentypen erkennt.
Mach ich die nächsten Tage.

**Comment by Morluktom** [comment]
Hallo, 
teste bitte die Version 0.0.6.
Am besten Adapter stoppen, und alle Datenpunkte löschen. Dann den Adapter wieder starten. 
Gruß
Tom

**Comment by fu-zhou** [comment]
Super, funktioniert, vielen Dank!
