### ISSUE TITLE
lg-ess-home Fehlermeldungen und Betriebszustand

### ISSUE THREAD

**Issue by Strommix** [Morluktom/ioBroker.lg-ess-home#32]
lg-ess-home.0 Instanz ist V0.3.0
NPM: 10.8.2
Node.js: v20.17.0
js-controller 6.0.11
Betriebssystem Linux Debian

Ich betreibe einen Wechselrichter von LG inkl. Batterie.
Diese werte ich aus mittels Adapter lg-ess-home.

Heute ist die Verbindung vom Wechselrichter und Energiemeter zusammen gebrochen.
Schuld dafür war ein Stromausfall in der Fritzbox.
Die Verbindung wird per Netzwerk getunnelt, darum der Ausfall.
Jetzt würde ich gerne den Betriebszustand des ESS auswerten und so etwas melden.
z.B Batterie Zustand, Fehler vom Wechselrichter usw.
Hat das schon mal einer gemacht und wenn ja wo kann man das abfragen und wie sehen die Meldungen aus ?

Identifiziert habe ich :
lg-ess-home.0.user.essinfo.home.operation.status
lg-ess-home.0.user.essinfo.home.pcs_fault.pcs_op_status
lg-ess-home.0.user.essinfo.home.pcs_fault.pcs_status

Da müsste nach meiner Auffassung was auszuwerten sein.
Nur wo kann man das nachlesen was da wie und wann passiert?
Experimentieren möchte ich da sehr ungerne.

**Comment by Morluktom** [comment]
Was ist der Fehler am Adapter?

**Comment by Strommix** [comment]
Hallo

Meine Frage zielt auf die Dokumentation des Adapters.
Ob das ein Fehler oder Fehlende Funktion oder Fehlerhafte Erwartungen sind seih mal dahin gestellt.
Um einen Bug im Adapter zu finden muss mal erst mal seine Funktion und Ausgaben wie Eingaben genau kennen.
Wenn man das so sehen möchte so ist das Fehlen (wenn es denn fehlt, möglicherweise habe ich es nur nicht gefunden) von Dokumentation ein Bug.
Aber das ist etwas weit hergeholt.
Zurück zu Thema, kannst du meine Frage beantworten ?

**Comment by Morluktom** [comment]
Hast Du einen Fehler in der App gesehen?
Der Adapter nutzt die App Schnittstelle.
Setzt die Daten welchen da kommen automatisch in Datenpunkte um.
Da kann je nach Software Version was hinzukommen oder auch raus fliegen.
=> Wenn Du in der App eine Anzeige hast, dann gibt das auch der Adapter her
