### ISSUE TITLE
LG ESS Home 15 Plus

### ISSUE THREAD

**Issue by bbfendt** [Morluktom/ioBroker.lg-ess-home#33]
Hallo, 

danke erstmal für den tollen Adapter ! 
Er arbeitet bisher relativ gut mit meinem neuen LG-Umrichter zusammen und ich kann damit einiges erfolgreich auslesen und in NodeRed visualisieren.
Im Protokoll bekomme ich allerdings nonstop folgende Meldungen: 

_

> ..
> lg-ess-home.0 | 2024-09-27 14:06:27.717 | error | [LG ESS] CreateDataPoint: TypeError: value.toLowerCase is not a function
> lg-ess-home.0 | 2024-09-27 14:06:27.715 | error | [LG ESS] CreateDataPoint: TypeError: value.toLowerCase is not a function
> lg-ess-home.0 | 2024-09-27 14:06:27.711 | error | [LG ESS] CreateDataPoint: TypeError: value.toLowerCase is not a function
> lg-ess-home.0 | 2024-09-27 14:05:27.641 | error | [LG ESS] CreateDataPoint: TypeError: value.toLowerCase is not a function
> lg-ess-home.0 | 2024-09-27 14:05:27.634 | error | [LG ESS] CreateDataPoint: TypeError: value.toLowerCase is not a function
> lg-ess-home.0 | 2024-09-27 14:05:27.615 | error | [LG ESS] CreateDataPoint: TypeError: value.toLowerCase is not a function
> lg-ess-home.0 | 2024-09-27 14:05:27.614 | error | [LG ESS] CreateDataPoint: TypeError: value.toLowerCase is not a function
> lg-ess-home.0 | 2024-09-27 14:05:27.601 | error | [LG ESS] CreateDataPoint: TypeError: value.toLowerCase is not a function
> lg-ess-home.0 | 2024-09-27 14:05:27.596 | error | [LG ESS] CreateDataPoint: TypeError: value.toLowerCase is not a function
> lg-ess-home.0 | 2024-09-27 14:05:27.580 | error | [LG ESS] CreateDataPoint: TypeError: value.toLowerCase is not a function
> ...

_

Was könnte da das Problem sein ?

Infos zum System:
Aktueller iobroker auf einem Raspi4
js-controller: 6.0.11
Node.js: v18.19.0
NPM: 10.2.3

Infos der Adapter-Instanz:
v0.3.0
Verbunden mit Host (grün)
Lebenszeichen (grün)
Verbunden mit Gerät oder Dienst (grün)
Installateur-Anmeldung ist deaktiviert

Danke und Gruß

**Comment by bbfendt** [comment]
Servus und danke für die schnelle Antwort.
Nachdem ich als Anfänger erstmal schauen musste wie ich von Github installieren kann (Stichwort Expertenmodus) habe ich das gerade getan und die Meldungen haben sich jetzt folgendermaßen geändert:

> 
> lg-ess-home.0 | 2024-09-27 16:16:19.997 | error | [LG ESS] WriteValue: Error: The state contains the forbidden properties installed, serial_no, sw_version, batt!
> -- | -- | -- | --
> lg-ess-home.0 | 2024-09-27 16:16:19.949 | error | [LG ESS] WriteValue: Error: The state contains the forbidden properties installed, serial_no, sw_version, batt!
> lg-ess-home.0 | 2024-09-27 16:16:19.944 | error | [LG ESS] WriteValue: Error: The state contains the forbidden properties installed, serial_no, sw_version, batt!
> lg-ess-home.0 | 2024-09-27 16:16:19.901 | error | [LG ESS] WriteValue: Error: The state contains the forbidden properties serial_no!
> lg-ess-home.0 | 2024-09-27 16:16:19.893 | error | [LG ESS] WriteValue: Error: The state contains the forbidden properties serial_no!
> lg-ess-home.0 | 2024-09-27 16:16:19.888 | error | [LG ESS] WriteValue: Error: The state contains the forbidden properties serial_no!
> lg-ess-home.0 | 2024-09-27 16:16:14.627 | info | State value to set for "lg-ess-home.0.user.essinfo.common.GRID.a_phase" has to be type "string" but received type "object"
> lg-ess-home.0 | 2024-09-27 16:16:14.621 | info | State value to set for "lg-ess-home.0.user.essinfo.common.GRID.active_power" has to be type "string" but received type "object"
> lg-ess-home.0 | 2024-09-27 16:16:14.603 | info | State value to set for "lg-ess-home.0.user.essinfo.common.ess_3.batt" has to be type "string" but received type "object"
> lg-ess-home.0 | 2024-09-27 16:16:14.599 | info | State value to set for "lg-ess-home.0.user.essinfo.common.ess_3.pv" has to be type "string" but received type "object"
> lg-ess-home.0 | 2024-09-27 16:16:14.585 | info | State value to set for "lg-ess-home.0.user.essinfo.common.ess_2.batt" has to be type "string" but received type "object"
> lg-ess-home.0 | 2024-09-27 16:16:14.570 | info | State value to set for "lg-ess-home.0.user.essinfo.common.ess_2.pv" has to be type "string" but received type "object"
> lg-ess-home.0 | 2024-09-27 16:16:14.567 | info | State value to set for "lg-ess-home.0.user.essinfo.common.ess_1.batt" has to be type "string" but received type "object"
> lg-ess-home.0 | 2024-09-27 16:16:14.558 | info | State value to set for "lg-ess-home.0.user.essinfo.common.ess_1.pv" has to be type "string" but received type "object"
> lg-ess-home.0 | 2024-09-27 16:16:14.555 | info | State value to set for "lg-ess-home.0.user.essinfo.common.ess_1.installed" has to be type "string" but received type "boolean"
> lg-ess-home.0 | 2024-09-27 16:16:09.358 | info | [LG ESS] Login success (user)
> lg-ess-home.0 | 2024-09-27 16:16:09.022 | info | starting.  Version 0.3.0 (non-npm: Morluktom/ioBroker.lg-ess-home) in  /opt/iobroker/node_modules/iobroker.lg-ess-home, node: v18.19.0,  js-controller: 6.0.11
> host.iobroker-pi4 | 2024-09-27 16:16:06.143 | info | instance system.adapter.lg-ess-home.0 in version "0.3.0" (non-npm: Morluktom/ioBroker.lg-ess-home) started with pid 7770

Es hat also schon mal etwas bewirkt :)

**Comment by Morluktom** [comment]
Stell mal das Log Level des Adapters auf Alles/silly und poste mal bitte das Log File.

**Comment by bbfendt** [comment]
Ich hoffe das reicht:
[LG_ESS_Adapter_Logfile.txt](https://github.com/user-attachments/files/17166610/LG_ESS_Adapter_Logfile.txt)

**Comment by Morluktom** [comment]
Ok das ist ja kein Home 8 oder Home 10.
Der liefert die Daten in ein etwas anderen Format.
Ich kann mir das mal ansehen ob ich das kompatibel hinbekommen. Wird aber etwas dauern.

**Comment by bbfendt** [comment]
Super - das wäre nett. 
Aber mach dir keinen Stress - die für mich wichtigsten Sachen funktionieren ja und ich bin nicht mehr auf die eher durchschnittlichen Apps von LG angewiesen...

![grafik](https://github.com/user-attachments/assets/04d4fa55-37df-4425-87fa-749446f22c3e)

**Comment by Morluktom** [comment]
Hallo, installier bitte nochmal die Github Version, und lösche alle Datenpunkte im IoBroker ab der Ebene User. Diese werden dann neu angelegt

**Comment by Morluktom** [comment]
Das wird noch nicht funktionieren, laut Log Antwortet der Wechselrichter auf die Anfragen mit Todo.
Mal sehen ob ich dahinter komme wie das bei dem geht

**Comment by bbfendt** [comment]
Alles gut - mein Issue ist ja gefixed.
Vielen Dank dafür !

**Comment by Morluktom** [comment]
Version 0.4.0 sollte jetzt auch das LG ESS 15 unterstützen
