### ISSUE TITLE
Fehler: Ip Adress: https://192.168.*.*/ is invalid

### ISSUE THREAD

**Issue by Snapergy** [Morluktom/ioBroker.lg-ess-home#8]
Hallo zusammen,

ich habe einen Wechselrichter von LG und wollte nun das ganze auf IoBroker einbinden. Nach ewigen hin und her habe ich jetzt endlich das Kommunikations-PW auslesen können. Leider scheitert der Versuch das ganze mit IoBroker zu verbinden an folgender Fehlermeldung:

Ip Adress: https://192.168.*.*/ is invalid

Bei der IP-Adresse handelt es sich um jene, die auch im Gerät (auslesen per App) angegeben ist. Gebe ich diese im Browser ein, leitet er mal auf die 192.168.23.1 um und manchmal erscheint eine weiße Seite, in welcher lediglich "Error" steht. Muss ich am Gerät selbst noch etwas einstellen?

EDIT: Ping auf die entsprechende IP-Adresse liefert eine Antwort...

**Comment by grex1975** [comment]
Hallo
bei mir ist die IP Adresse des Wechselrichters im lokalen Netz 192.168.0.109
Ping liefert Antwort,
Eingabe im Browser funktioniert nicht. Er leitet um auf 192.168.23.1 und bricht wegen Zeitüberschreitung ab.
Das Datensammeln via IOBroker funktioniert aber!
LG

**Comment by Snapergy** [comment]
Leider klappt das Datensammeln bei mir nicht, da er die IP-Adresse als Invalid ansieht :( Mir würde das schon reichen, wenn er die Daten sammelt. Per Browser muss ich nicht zwingend drauf zugreifen können

**Comment by grex1975** [comment]
Fröhliches Datensammeln und Auswerten :-)

**Comment by Morluktom** [comment]
Hallo,

Über einen Browser wirst Du nicht so ohne weiteres auf den Wechselrichter kommen.
Dieser erfordert ja eine Anmeldung.
Ich verstehe Dein Problem nicht.
Wenn es erledigt ist bitte schließen.

Gruß 

Tom

**Comment by Snapergy** [comment]
Problem war, dass in der IoBroker-Instanz bei den Einstellungen der Default-Wert der IP-Adresse glaube  "https://192.168.23.1" war. Ich habe lediglich die letzten beiden Stellen angepasst und es wurde dann im Log immer die o.s. Fehlermeldung ausgegeben. Ich hatte es dann lediglich mit "192.168.*.*" versucht und es hat dann geklappt
